{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "eks-upgrade-planner.fullname" . }}
  labels:
    {{- include "eks-upgrade-planner.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.blockMetricsPath }}
    nginx.ingress.kubernetes.io/server-snippet: |
      location = /metrics {
        return 404;
      }
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "eks-upgrade-planner.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
