grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: eks-planner-local
  sidecar:
    image:
      registry: docker.io
      repository: kiwigrid/k8s-sidecar
      tag: 2.7.3
    dashboards:
      enabled: true
    datasources:
      enabled: true
  additionalDataSources:
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki-gateway.observability.svc.cluster.local
    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: http://tempo.observability.svc.cluster.local:3200
      jsonData:
        tracesToLogsV2:
          datasourceUid: loki
          spanStartTimeShift: -5m
          spanEndTimeShift: 5m
          tags: [{ key: service.name, value: service }]
        tracesToMetrics:
          datasourceUid: prometheus
        serviceMap:
          datasourceUid: prometheus
        nodeGraph:
          enabled: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    scrapeInterval: 15s
    retention: 3d
    enableRemoteWriteReceiver: true
    image:
      registry: docker.io
      repository: prom/prometheus
      tag: v3.12.0

alertmanager:
  enabled: true
  alertmanagerSpec:
    image:
      registry: docker.io
      repository: prom/alertmanager
      tag: v0.32.1

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
  image:
    registry: docker.io
    repository: prom/node-exporter
    tag: v1.11.1
    distroless: false

prometheusOperator:
  image:
    registry: ghcr.io
    repository: prometheus-operator/prometheus-operator
  prometheusConfigReloader:
    image:
      registry: ghcr.io
      repository: prometheus-operator/prometheus-config-reloader
  prometheusDefaultBaseImageRegistry: docker.io
  prometheusDefaultBaseImage: prom/prometheus
  alertmanagerDefaultBaseImageRegistry: docker.io
  alertmanagerDefaultBaseImage: prom/alertmanager

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false
